require('dotenv').config();
const fs = require('fs');

const supabaseUrl = process.env.SUPABASE_URL;
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
    console.error('Error: SUPABASE_URL or SUPABASE_ANON_KEY is missing in environment variables.');
    console.error('Please verify your .env file or Netlify environment settings.');
    // Don't fail the build immediately to allow debugging, but warn loudly
    // process.exit(1); 
}

const content = `// Supabase Configuration
// Auto-generated by build.js
const SUPABASE_URL = '${supabaseUrl || "MISSING_URL"}';
const SUPABASE_ANON_KEY = '${supabaseAnonKey || "MISSING_KEY"}';

// Initialize Supabase Client
if (typeof supabase !== 'undefined') {
    window.supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
} else {
    console.error('Supabase library not loaded. Make sure to include the Supabase CDN script before this file.');
}
`;

fs.writeFileSync('supabase-config.js', content);
console.log('supabase-config.js generated successfully.');
